server:
  port: 8082
  servlet:
    context-path: /pharmacy

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/epharmacy
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Mushfig2023_


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: mikayilzademusviq98@gmail.com
    password: uutxsotoycfvpzwt
    properties.mail.smtp:
      auth: true
      starttls.enable: true

